# A MODIFIER =====================================================================================


# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Nom du site
author: Votre nom et prénom
copyright: "Licence juridique Creative Commons CC-BY-SA"  # Copyright year to be placed in the footer
logo: logo.png


# Information about where the book exists on the web
repository:
  url: https://github.com/<nom github>/<votre nom de projet>  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)


# NE PAS MODIFIER =====================================================================================


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false


only_build_toc_files: true

exclude_patterns: [.virtual_documents/*]


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


launch_buttons:
  thebe: true
